# Generated by Django 4.0.5 on 2022-09-02 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masdatosusuario',
            name='contenido',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
