# Generated by Django 4.0.5 on 2022-09-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_masdatosusuario_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masdatosusuario',
            name='contenido',
        ),
        migrations.AddField(
            model_name='masdatosusuario',
            name='perfil_url',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
